__title__ = "LatticeJSON"
__description__ = "A JSON based lattice file format"
__url__ = "https://github.com/andreasfelix/latticejson"
__version__ = "0.0.4"
__author__ = "Felix Andreas"
__license__ = "GNU General Public License v3.0"
