%ignore /\s+/
%import common (NUMBER, CNAME)

?start     : assignment | expr
assignment : expr "sto" CNAME
?expr      : NUMBER        -> number
           | CNAME         -> variable
           | function
           | binary
!function  : expr ("exp" | "sin" | "cos" | "tan" | "asin" | "acos" | "atan")
?binary    : expr expr "+" -> add
           | expr expr "-" -> sub
           | expr expr "*" -> mul
           | expr expr "/" -> div
